# Generated by Django 4.2.4 on 2023-08-13 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipie',
            old_name='recipie_decription',
            new_name='recipie_description',
        ),
    ]
