# Generated by Django 4.2.4 on 2023-08-13 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipie', '0002_rename_recipie_decription_recipie_recipie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
