# Generated by Django 4.2.4 on 2023-08-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='number',
            new_name='mobile',
        ),
    ]
